### ISSUE TITLE
Launched)

### ISSUE THREAD

**Issue by Claus1s** [xtekkyx/Mevbot#3]
I launched it on the BSC network.
Everything is going well; I made a profit of 1.28 BNB.
I'm very happy about it!))
Can I find out what the upcoming update will be?

**Comment by xtekkyx** [comment]
Improvements to the interface are planned, where you will be able to customize it for a specific token. For instance, if you create and launch your own token, you will be able to run the bot for your cryptocurrency

**Comment by Claus1s** [comment]
ok,very well))Thank you ser
